name: Node.js Package pre-released
on:
  release:
    types: [prereleased]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      # Setup .npmrc file to publish to npm
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          registry-url: 'https://registry.npmjs.org'
          cache: 'npm'
      - id: get_version
        uses: battila7/get-version-action@v2
      - name: set package version
        run: npm version --allow-same-version --no-git-tag-version ${{ steps.get_version.outputs.version-without-v }}
      - name: Install Dependencies
        run: npm install
      - run: npm publish --access --tag next
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
